//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atos.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid Id { get; set; }
        public int SourceId { get; set; }
        public int TargetId { get; set; }
        public byte[] Raw { get; set; }
        public string Hex { get; set; }
        public long Hash { get; set; }
        public string PayloadRaw { get; set; }
        public int SequenceNumber { get; set; }
        public string PayloadType { get; set; }
        public int PayloadTargetId { get; set; }
        public int PayloadTaskNumber { get; set; }
        public int PayloadArg0 { get; set; }
        public int PayloadArg1 { get; set; }
        public int PayloadArg2 { get; set; }
        public int PayloadArg3 { get; set; }
        public bool FromClient { get; set; }
        public Nullable<int> BadMessage { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public bool Legacy { get; set; }
    }
}
